apiVersion: backstage.io/v1alpha1 
kind: Component
metadata:
  name: emailservice
  description: The place to be, for great artists
  supportGroup: Eng - ServiceNow
  techOwner:
    name: Jon Giara
    email: jon@rapdev.io
  links:
      - title: Website
        url: http://rapdev.io
spec:
  type: service
  lifecycle: production
  owner: sn-engineering
  system: rapdev-portal
  providesApis:
    - email-api
  businessApps:
    - name: RapDev.io Website
  deployedEnvironments:
    - name: production
      tags:
        app.kubernetes.io/component: emailservice
        env: production
    - name: test
      tags:
        app.kubernetes.io/component: emailservice
        env: test
    - name: development
      tags:
        app.kubernetes.io/component: emailservice
        env: dev
