apiVersion: backstage.io/v1alpha1  
kind: Component
metadata:
  name: frontend
  description: Service for frontend
  supportGroup: Eng - ServiceNow
  techOwner:
    name: Jon Giara
    email: jon@rapdev.io
  links:
      - title: Website
        url: http://rapdev.io
spec:
  type: service
  lifecycle: production
  owner: sn-engineering
  system: rapdev-portal
  providesApis:
    - frontend-api
  businessApps:
    - name: RapDev.io Website
  deployedEnvironments:
    - name: production
      tags:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/env: prod
    - name: test
      tags:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/env: test
    - name: development
      tags:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/env: dev
