apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-secret-list-binding
  namespace: default
subjects:
- kind: User  
  name: deployer  
  apiGroup: ""
roleRef:
  kind: Role
  name: secret-list-role
  apiGroup: rbac.authorization.k8s.io